name: hon_app
description: A Book(Hon) App.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.7
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  hive: ^2.0.5
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/svg/
    - assets/images/

  uses-material-design: true
