// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC1-4z5AXHaq385mzhZ54b_S8Rc0GF5MM',
    appId: '1:839162615817:android:cc3f70e843376d8e8580d8',
    messagingSenderId: '839162615817',
    projectId: 'hon-app-e45c2',
    storageBucket: 'hon-app-e45c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwCNOAS1dU0o84wUb_jcge5a98LXuAHks',
    appId: '1:839162615817:ios:30eb1ede73c6185e8580d8',
    messagingSenderId: '839162615817',
    projectId: 'hon-app-e45c2',
    storageBucket: 'hon-app-e45c2.appspot.com',
    iosClientId: '839162615817-c7j6ojing35j1al2isssiha0u7h104pl.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
